### ISSUE TITLE
Improve player_history command

### ISSUE THREAD

**Issue by FAZuH** [FAZuH/faz-bot#60]
### Current implementation

 `player_history` command currently displays numerical differences in player stats over a selected time period. Initially,  the result shows the total stat differences. Users can then select which data (either the total or character-specific stats) they want to view using provided buttons.

### Planned implementation

- Show total stat differences initially
- `nextcord.ui.StringSelect` to choose "data". Choose total/character-specific data.
- UI component to choose "id" to view. Choose all/id-specific view

For data type selection UI, choose:
1. Two Buttons under character StringSelect
2. Two Buttons above character StringSelect
3. StringSelect under character StringSelect
4. StringSelect above character StringSelect
5. StringSelect next to character StringSelect

## Tasks

- [x] Add tests for select as dataframe method for `character_history`
- [x] Implement a select as dataframe method for `character_history`
- [x] Make the test cases pass
- [x] Subclass `nextcord.ui.StringSelect` for choosing data type
- [x] Subclass `enum.Enum` for select options
- [x] Make test cases for the subclass & test it
- [x] Test it on dev: Check behaviour when interacted
- [x] Create a class representing options for character selection
- [x] Subclass `nextcord.ui.StringSelect` for choosing arbitrary character
- [x] Make test cases and ensure test passes
- [x] Test it on dev: Check behaviour when interacted
- [ ] Subclass `nextcord.ui.StringSelect` for choosing specific id
- [ ] Create a class to represent valid ids to choose. Make sure it:
    - Displayed nicely to the user
    - Works for matching user option with the corresponding id internally
